### PR TITLE
Homerow navigation and Quit-key

### PR DESCRIPTION
**Pull request by GregCM**
Some quick key-binds to move around and exit. Thoughts?

### CODE REVIEW

**Comment by bajaco** [comment]
Thanks, the only thing though is 3 won't always be quit, there could be any number of functions.

**Comment by GregCM** [comment]
Yes I figured that'd be the case, but wasn't sure how you might prefer to handle that dynamically. Return the length of the function list is my best guess.

**Comment by bajaco** [comment]
Can you change it to len(self.options) ?
Or I can accept the request and change it after.

**Comment by GregCM** [comment]
Done.

Kind of extra, but wouldn't a call to Menu.get_quit() do the job too?

**Comment by bajaco** [comment]
Yeah that would be fine too, I forgot that the menu function is held in the list.

**Pull request merged**
